from services.auth_service import connected_login_methods_count, bundle_role, load_user
from services.mail_service import (
    send_email,
    _comic_email_shell,
    send_verification_email,
    send_email_change_verification,
    send_login_otp,
)
from services.file_service import (
    allowed_file,
    allowed_game_file,
    save_file,
    get_clamd_client,
    scan_filestorage_for_malware,
    save_game_file,
)
from services.game_service import (
    calculate_game_revenue,
    calculate_display_price,
    calculate_review_score,
    _get_tag_set,
    get_popular_games,
    get_recommended_games,
    update_daily_stats,
    check_sales_expiry,
)
from services.cart_service import (
    _generate_cart_token,
    _valid_cart_token,
    _merge_guest_cart,
    _compute_bundle_alerts,
)
from services.payment_service import fulfill_checkout, fulfill_gift
from services.badge_service import (
    get_all_badges,
    get_badge_definition,
    evaluate_eligible_badges,
    sync_user_badges,
    get_user_badges,
    get_featured_badge,
    set_featured_badge,
    grant_manual_badge,
)

__all__ = [
    "connected_login_methods_count",
    "bundle_role",
    "load_user",
    "send_email",
    "_comic_email_shell",
    "send_verification_email",
    "send_email_change_verification",
    "send_login_otp",
    "allowed_file",
    "allowed_game_file",
    "save_file",
    "get_clamd_client",
    "scan_filestorage_for_malware",
    "save_game_file",
    "calculate_game_revenue",
    "calculate_display_price",
    "calculate_review_score",
    "_get_tag_set",
    "get_popular_games",
    "get_recommended_games",
    "update_daily_stats",
    "check_sales_expiry",
    "_generate_cart_token",
    "_valid_cart_token",
    "_merge_guest_cart",
    "_compute_bundle_alerts",
    "fulfill_checkout",
    "fulfill_gift",
    "get_all_badges",
    "get_badge_definition",
    "evaluate_eligible_badges",
    "sync_user_badges",
    "get_user_badges",
    "get_featured_badge",
    "set_featured_badge",
    "grant_manual_badge",
]
